### ISSUE TITLE
read it. NOW!

### ISSUE THREAD

**Issue by mohamed2338** [iwoplaza/MoBends#162]
I'm always frustrated when I click right click then the character does the animation like I am punching a wood... imagine that I am put a couch mod (and that's what I am doing) and I want to sit on the couch then I being like punching and my leg is Penetrates the couch I HATE THAT!!... and why you don't read the comments that your downloaders say on curseforge website they are sad man and what they say that they want to you make an update with 1.16.1 and I want that... plz make it thanks.

**Comment by partyp770** [comment]
Really bad first issue. The creator of the mod does this stuff in his free time, and he is actively working on porting it to 1.16, alongside a rewrite of the major animation systems.

I don't think that the leg clipping through a couch/stair/slab is really a priority for him at the moment. It's not even a vanilla feature, more just a hacky plugin workaround for roleplaying purposes.

If you wish to keep up with development progress, feel free to join the discord server linked in the readme. Otherwise, please don't harass the devs with an obnoxious rant for an issue they are very well aware of.

**Comment by iwoplaza** [comment]
@partyp770 said it best. Thank you for handling this issue! Closing now.
